server:
  port: 80

spring:
  profiles:
    active: test
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
---
filepath: d:/test
spring:
  config:
    activate:
      on-profile: dev
---
filepath: /opt/WebTool
spring:
  config:
    activate:
      on-profile: test